<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DbExplorer.Providers.Postgres</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DbExplorer.Core\DbExplorer.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Npgsql" Version="8.0.5" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
  </ItemGroup>
</Project>
