namespace DbExplorer.Application.Design;

/// <summary>One column of a table being designed. <see cref="Type"/> is the base type (nvarchar, decimal); <see cref="Size"/>
/// holds what goes in its brackets ("100", "max", "18,2"). A type typed with its brackets ("nvarchar(100)") works too.</summary>
public sealed record ColumnDesign
{
    public string Name { get; init; } = "";

    /// <summary>The column's name on the server when the design alters an existing table; null for a new column.</summary>
    public string? OriginalName { get; init; }

    public string Type { get; init; } = "";
    public string? Size { get; init; }
    public bool IsNullable { get; init; } = true;
    public bool IsPrimaryKey { get; init; }

    /// <summary>Values generated by the server (SQL Server IDENTITY, PostgreSQL GENERATED BY DEFAULT AS IDENTITY).</summary>
    public bool IsIdentity { get; init; }

    /// <summary>A default expression written as SQL (0, N'new', SYSUTCDATETIME(), now()).</summary>
    public string? Default { get; init; }

    /// <summary>The type without its brackets, lowercased: "nvarchar" for "NVARCHAR(100)".</summary>
    public string BaseType
    {
        get
        {
            var type = Type.Trim();
            var open = type.IndexOf('(');
            return (open < 0 ? type : type[..open]).Trim().ToLowerInvariant();
        }
    }

    /// <summary>The size in effect: <see cref="Size"/>, or what was typed in the type's own brackets.</summary>
    public string? EffectiveSize
    {
        get
        {
            if (!string.IsNullOrWhiteSpace(Size)) return Size.Trim();
            var type = Type.Trim();
            var open = type.IndexOf('(');
            var close = type.LastIndexOf(')');
            return open >= 0 && close > open ? type[(open + 1)..close].Trim() : null;
        }
    }

    /// <summary>The type as it goes in the script: nvarchar(100), decimal(18,2), int.</summary>
    public string FullType
    {
        get
        {
            var type = Type.Trim();
            var open = type.IndexOf('(');
            // timestamp(3) with time zone: words after the brackets stay where they are.
            if (string.IsNullOrWhiteSpace(Size) && open >= 0 && type.LastIndexOf(')') is var close && close > open && close < type.Length - 1)
                return type;
            var name = open < 0 ? type : type[..open].Trim();
            return EffectiveSize is { Length: > 0 } size ? $"{name}({size})" : name;
        }
    }

    /// <summary>A not-null column, as the script writes it: primary key columns are never nullable.</summary>
    public bool WritesNotNull => IsPrimaryKey || !IsNullable;
}

/// <summary>A single-column foreign key from the table to an existing table's key. When altering, a key keeps the name
/// it has on the server, which is how the script tells an unchanged key from a new one.</summary>
public sealed record ForeignKeyDesign
{
    /// <summary>Empty: named FK_Table_Parent by the script.</summary>
    public string Name { get; init; } = "";
    public string Column { get; init; } = "";
    public string ReferencedSchema { get; init; } = "";
    public string ReferencedTable { get; init; } = "";
    public string ReferencedColumn { get; init; } = "";
}

public sealed record IndexDesign
{
    /// <summary>Empty: named IX_Table_Column(s) (UX_ when unique) by the script.</summary>
    public string Name { get; init; } = "";
    public IReadOnlyList<string> Columns { get; init; } = [];
    public bool IsUnique { get; init; }

    /// <summary>Read from a UNIQUE constraint (PostgreSQL, SQL Server): dropped with DROP CONSTRAINT, not DROP INDEX.</summary>
    public bool IsConstraint { get; init; }
}

/// <summary>A table as the table designer holds it: everything the CREATE TABLE script is made from, or, next to the
/// design read from the server, what the ALTER TABLE script is made from.</summary>
public sealed record TableDesign
{
    /// <summary>Database the table is created in; empty for the connection's own database.</summary>
    public string Database { get; init; } = "";
    public string Schema { get; init; } = "";
    public string Name { get; init; } = "";
    public IReadOnlyList<ColumnDesign> Columns { get; init; } = [];
    public IReadOnlyList<ForeignKeyDesign> ForeignKeys { get; init; } = [];
    public IReadOnlyList<IndexDesign> Indexes { get; init; } = [];

    /// <summary>The primary key constraint's name; empty for PK_Table.</summary>
    public string PrimaryKeyName { get; init; } = "";

    public IEnumerable<ColumnDesign> PrimaryKey => Columns.Where(c => c.IsPrimaryKey && c.Name.Trim().Length > 0);

    public ColumnDesign? Column(string name) => Columns.FirstOrDefault(c => Same(c.Name.Trim(), name.Trim()));

    /// <summary>A copy with one column (matched by name) changed.</summary>
    public TableDesign WithColumn(string name, Func<ColumnDesign, ColumnDesign> change) =>
        this with { Columns = Columns.Select(c => Same(c.Name.Trim(), name.Trim()) ? change(c) : c).ToList() };

    /// <summary>A copy with a column renamed, along with the foreign keys and indexes that use it.</summary>
    public TableDesign RenameColumn(string name, string newName)
    {
        string Rename(string c) => Same(c.Trim(), name.Trim()) ? newName : c;
        return this with
        {
            Columns = Columns.Select(c => Same(c.Name.Trim(), name.Trim()) ? c with { Name = newName } : c).ToList(),
            ForeignKeys = ForeignKeys.Select(f => f with { Column = Rename(f.Column) }).ToList(),
            Indexes = Indexes.Select(i => i with { Columns = i.Columns.Select(Rename).ToList() }).ToList()
        };
    }

    public TableDesign AddColumn(ColumnDesign column, bool first = false) =>
        this with { Columns = first ? [column, .. Columns] : [.. Columns, column] };

    public TableDesign AddForeignKey(ForeignKeyDesign foreignKey) => this with { ForeignKeys = [.. ForeignKeys, foreignKey] };

    public TableDesign AddIndex(IndexDesign index) => this with { Indexes = [.. Indexes, index] };

    internal static bool Same(string a, string b) => string.Equals(a, b, StringComparison.OrdinalIgnoreCase);
}
