using DbExplorer.Application.Copy;
using DbExplorer.Application.Design;
using DbExplorer.Application.Metadata;
using DbExplorer.Core.Models;

namespace DbExplorer.Tests;

public class TableDesignerTests
{
    private static readonly DesignContext Shop = DesignContext.From(TestSnapshots.Shop(), SqlDialect.SqlServerKey);

    private static TableDesign Invoices(params ColumnDesign[] columns) => new()
    {
        Schema = "dbo",
        Name = "Invoices",
        Columns = columns.Length > 0 ? columns : [Key("InvoiceId"), Col("CustomerId", "int", nullable: false), Col("Total", "decimal", "18,2")]
    };

    private static ColumnDesign Key(string name) => new() { Name = name, Type = "int", IsPrimaryKey = true, IsIdentity = true, IsNullable = false };

    private static ColumnDesign Col(string name, string type, string? size = null, bool nullable = true) =>
        new() { Name = name, Type = type, Size = size, IsNullable = nullable };

    private static DesignSuggestion Find(IReadOnlyList<DesignSuggestion> suggestions, string key) =>
        Assert.Single(suggestions, s => s.Key == key);

    // ----- Script -----

    [Fact]
    public void Sql_server_script_has_columns_key_foreign_key_and_index()
    {
        var design = Invoices() with
        {
            ForeignKeys = [new ForeignKeyDesign { Column = "CustomerId", ReferencedSchema = "dbo", ReferencedTable = "Customers", ReferencedColumn = "CustomerId" }],
            Indexes = [new IndexDesign { Columns = ["CustomerId"] }]
        };
        design = design.AddColumn(Col("Status", "nvarchar", "20", nullable: false) with { Default = "N'new'" });

        var script = TableScriptBuilder.Build(design, SqlDialect.SqlServerKey);

        Assert.Equal(
            "CREATE TABLE [dbo].[Invoices] (\n" +
            "    [InvoiceId] int IDENTITY(1,1) NOT NULL,\n" +
            "    [CustomerId] int NOT NULL,\n" +
            "    [Total] decimal(18,2) NULL,\n" +
            "    [Status] nvarchar(20) NOT NULL DEFAULT N'new',\n" +
            "    CONSTRAINT [PK_Invoices] PRIMARY KEY ([InvoiceId]),\n" +
            "    CONSTRAINT [FK_Invoices_Customers] FOREIGN KEY ([CustomerId])\n" +
            "        REFERENCES [dbo].[Customers] ([CustomerId])\n" +
            ");\n" +
            "CREATE INDEX [IX_Invoices_CustomerId] ON [dbo].[Invoices] ([CustomerId]);\n",
            script);
    }

    [Fact]
    public void Postgres_script_uses_identity_and_creates_a_missing_schema()
    {
        var design = new TableDesign
        {
            Schema = "billing",
            Name = "invoices",
            Columns = [new ColumnDesign { Name = "id", Type = "bigint", IsPrimaryKey = true, IsIdentity = true }, Col("note", "text")],
            Indexes = [new IndexDesign { Columns = ["note"], IsUnique = true }]
        };

        var script = TableScriptBuilder.Build(design, SqlDialect.PostgresKey, createSchema: true);

        Assert.StartsWith("CREATE SCHEMA IF NOT EXISTS \"billing\";\nCREATE TABLE \"billing\".\"invoices\" (\n", script);
        Assert.Contains("    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n", script);
        Assert.Contains("CONSTRAINT \"PK_invoices\" PRIMARY KEY (\"id\")", script);
        Assert.Contains("CREATE UNIQUE INDEX \"UX_invoices_note\" ON \"billing\".\"invoices\" (\"note\");", script);
    }

    [Fact]
    public void A_type_typed_with_its_size_is_kept_and_primary_keys_are_never_null()
    {
        var c = new ColumnDesign { Name = "Code", Type = "NVARCHAR(10)", IsPrimaryKey = true, IsNullable = true };
        Assert.Equal("nvarchar", c.BaseType);
        Assert.Equal("10", c.EffectiveSize);
        Assert.Equal("NVARCHAR(10)", c.FullType);
        Assert.Contains("[Code] NVARCHAR(10) NOT NULL", TableScriptBuilder.Build(new TableDesign { Name = "T", Columns = [c] }, SqlDialect.SqlServerKey));
    }

    [Fact]
    public void Two_keys_to_the_same_parent_are_named_by_column()
    {
        var design = new TableDesign
        {
            Name = "Shipments",
            Columns = [Col("FromId", "int"), Col("ToId", "int")],
            ForeignKeys =
            [
                new ForeignKeyDesign { Column = "FromId", ReferencedSchema = "dbo", ReferencedTable = "Addresses", ReferencedColumn = "Id" },
                new ForeignKeyDesign { Column = "ToId", ReferencedSchema = "dbo", ReferencedTable = "Addresses", ReferencedColumn = "Id" }
            ]
        };
        var script = TableScriptBuilder.Build(design, SqlDialect.SqlServerKey);
        Assert.Contains("[FK_Shipments_FromId]", script);
        Assert.Contains("[FK_Shipments_ToId]", script);
    }

    // ----- Suggestions: errors -----

    [Fact]
    public void A_name_already_taken_and_a_missing_name_are_errors()
    {
        var taken = TableDesignAdvisor.Review(Invoices() with { Name = "customers" }, Shop);
        Assert.Equal(DesignSeverity.Error, Find(taken, "exists").Severity);

        var unnamed = TableDesignAdvisor.Review(Invoices() with { Name = " " }, Shop);
        Assert.Equal(DesignSeverity.Error, Find(unnamed, "name").Severity);
    }

    [Fact]
    public void Duplicate_columns_and_identity_on_text_are_errors()
    {
        var review = TableDesignAdvisor.Review(Invoices(Key("InvoiceId"), Col("Total", "int"), Col("total", "int"), Col("Ref", "nvarchar", "10") with { IsIdentity = true }), Shop);
        Assert.Equal(DesignSeverity.Error, Find(review, "duplicate:Total").Severity);
        Assert.Equal(DesignSeverity.Error, Find(review, "identity-count").Severity);

        var identity = Find(review, "identity-type:Ref");
        var fixedDesign = identity.Fix!(Invoices(Col("Ref", "nvarchar", "10") with { IsIdentity = true }));
        Assert.Equal("int", fixedDesign.Column("Ref")!.FullType);
    }

    [Fact]
    public void A_foreign_key_to_a_table_that_does_not_exist_is_an_error()
    {
        var design = Invoices() with { ForeignKeys = [new ForeignKeyDesign { Column = "CustomerId", ReferencedSchema = "dbo", ReferencedTable = "Clients", ReferencedColumn = "Id" }] };
        Assert.Equal(DesignSeverity.Error, Find(TableDesignAdvisor.Review(design, Shop), "fk-table:CustomerId").Severity);
    }

    [Fact]
    public void Errors_come_first()
    {
        var review = TableDesignAdvisor.Review(Invoices(Col("CustomerId", "nvarchar"), Col("Total", "float")) with { Name = "" }, Shop);
        Assert.Equal(DesignSeverity.Error, review[0].Severity);
        Assert.True(review.Select(s => s.Severity).SequenceEqual(review.Select(s => s.Severity).Order()));
    }

    // ----- Suggestions: warnings and their fixes -----

    [Fact]
    public void A_column_named_like_an_existing_key_gets_a_foreign_key_and_its_index()
    {
        var design = Invoices();
        var fk = Find(TableDesignAdvisor.Review(design, Shop), "fk-candidate:CustomerId");
        Assert.Equal(DesignSeverity.Warning, fk.Severity);
        Assert.Contains("dbo.Customers", fk.Title);

        design = fk.Fix!(design);
        var added = Assert.Single(design.ForeignKeys);
        Assert.Equal(("CustomerId", "dbo", "Customers", "CustomerId"), (added.Column, added.ReferencedSchema, added.ReferencedTable, added.ReferencedColumn));

        var review = TableDesignAdvisor.Review(design, Shop);
        Assert.DoesNotContain(review, s => s.Key == "fk-candidate:CustomerId");
        design = Find(review, "fk-index:CustomerId").Fix!(design);
        Assert.Equal(["CustomerId"], Assert.Single(design.Indexes).Columns);
        Assert.DoesNotContain(TableDesignAdvisor.Review(design, Shop), s => s.Key == "fk-index:CustomerId");
    }

    [Fact]
    public void A_reference_with_the_wrong_type_gets_the_parents_type()
    {
        var design = Invoices(Key("InvoiceId"), Col("ProductId", "nvarchar", "20"));
        var fk = Find(TableDesignAdvisor.Review(design, Shop), "fk-candidate:ProductId");
        Assert.Contains("type differs", fk.Title);

        design = fk.Fix!(design);
        Assert.Equal("int", design.Column("ProductId")!.FullType);
        Assert.Single(design.ForeignKeys);
        Assert.DoesNotContain(TableDesignAdvisor.Review(design, Shop), s => s.Key.StartsWith("fk-type"));
    }

    [Fact]
    public void A_table_without_a_primary_key_gets_one()
    {
        var withId = Invoices(Col("InvoiceId", "int", nullable: true), Col("Total", "decimal", "18,2"));
        var make = Find(TableDesignAdvisor.Review(withId, Shop), "no-pk");
        Assert.Equal("Make InvoiceId the key", make.FixLabel);
        var key = make.Fix!(withId).Column("InvoiceId")!;
        Assert.True(key.IsPrimaryKey && key.IsIdentity && !key.IsNullable);

        var withoutId = Invoices(Col("Total", "decimal", "18,2"));
        var added = Find(TableDesignAdvisor.Review(withoutId, Shop), "no-pk").Fix!(withoutId);
        // Shop names keys after their table (Customers.CustomerId), so the new key follows suit.
        Assert.Equal("InvoiceId", added.Columns[0].Name);
        Assert.True(added.Columns[0].IsPrimaryKey);
    }

    [Theory]
    [InlineData("OrderDate", "nvarchar", "20", "date-type", "date")]
    [InlineData("CreatedAt", "varchar", "30", "date-type", "datetime2")]
    [InlineData("UnitPrice", "float", null, "money", "decimal(18,2)")]
    [InlineData("ExternalId", "nvarchar", "50", "id-text", "int")]
    [InlineData("Email", "nvarchar", "max", "unbounded", "nvarchar(320)")]
    [InlineData("Notes", "varchar", null, "length", "varchar(100)")]
    [InlineData("Rate", "decimal", null, "precision", "decimal(18,2)")]
    [InlineData("IsPaid", "int", null, "flag", "bit")]
    [InlineData("Body", "ntext", null, "deprecated", "nvarchar(max)")]
    [InlineData("PaidOn", "datetime", null, "datetime", "datetime2")]
    public void Types_that_look_wrong_for_the_name_get_a_one_click_fix(string column, string type, string? size, string rule, string expected)
    {
        var design = Invoices(Key("InvoiceId"), Col(column, type, size));
        var suggestion = Find(TableDesignAdvisor.Review(design, Shop), $"{rule}:{column}");
        Assert.Equal(expected, suggestion.Fix!(design).Column(column)!.FullType);
    }

    [Fact]
    public void Well_typed_columns_get_no_type_suggestions()
    {
        var design = Invoices(Key("InvoiceId"), Col("OrderDate", "date"), Col("UnitPrice", "decimal", "18,2"), Col("Email", "nvarchar", "320"),
            Col("IsPaid", "bit"), Col("Paid", "int"), Col("Guid", "uniqueidentifier"));
        Assert.DoesNotContain(TableDesignAdvisor.Review(design, Shop), s => s.Severity != DesignSeverity.Tip || s.Key.Contains(':'));
    }

    [Fact]
    public void Postgres_types_are_suggested_on_postgres()
    {
        var context = DesignContext.Empty(SqlDialect.PostgresKey);
        var design = new TableDesign { Name = "events", Columns = [Key("id") with { Type = "integer" }, Col("created_at", "text"), Col("happened", "timestamp")] };
        var review = TableDesignAdvisor.Review(design, context);
        Assert.Equal("timestamptz", Find(review, "date-type:created_at").Fix!(design).Column("created_at")!.FullType);
        Assert.Equal("timestamptz", Find(review, "timestamptz:happened").Fix!(design).Column("happened")!.FullType);
    }

    // ----- Suggestions: consistency with the database -----

    private static DesignContext SnakeShop()
    {
        string[] tables = ["customers", "orders", "order_lines", "products"];
        var snapshot = new MetadataSnapshot
        {
            Objects = tables.Select(t => new DbObject { Schema = "public", Name = t, Type = DbObjectType.Table }).ToList(),
            Columns = tables.SelectMany(t => new[]
            {
                new DbColumn { Schema = "public", Table = t, Name = "id", Ordinal = 1, DataType = "integer", BaseType = "int4", IsPrimaryKey = true },
                new DbColumn { Schema = "public", Table = t, Name = "created_at", Ordinal = 2, DataType = "timestamp with time zone", BaseType = "timestamptz" }
            }).ToList(),
            Modules = [],
            ForeignKeys = [],
            Indexes = [],
            RefreshedAt = DateTimeOffset.Now
        };
        return DesignContext.From(snapshot, SqlDialect.PostgresKey);
    }

    [Fact]
    public void Conventions_are_learned_from_the_existing_tables()
    {
        var snake = SnakeShop();
        Assert.Equal(NamingStyle.Snake, snake.TableStyle);
        Assert.Equal(NamingStyle.Snake, snake.ColumnStyle);
        Assert.True(snake.PluralTables);
        Assert.Equal(KeyNaming.Id, snake.KeyNaming);
        Assert.Equal("created_at", Assert.Single(snake.CommonAuditColumns).Name);

        Assert.Equal(KeyNaming.TableId, Shop.KeyNaming);
        Assert.True(Shop.PrefersUnicode);
    }

    [Fact]
    public void Names_that_break_the_convention_are_renamed_with_their_keys_and_indexes()
    {
        var context = SnakeShop();
        var design = new TableDesign
        {
            Schema = "public",
            Name = "Invoice",
            Columns = [Key("id") with { Type = "integer" }, Col("CustomerId", "integer"), Col("created_at", "timestamptz")],
            ForeignKeys = [new ForeignKeyDesign { Column = "CustomerId", ReferencedSchema = "public", ReferencedTable = "customers", ReferencedColumn = "id" }],
            Indexes = [new IndexDesign { Columns = ["CustomerId"] }]
        };
        var review = TableDesignAdvisor.Review(design, context);

        Assert.Equal("Rename to invoice", Find(review, "table-style").FixLabel);
        Assert.Equal("Rename to Invoices", Find(review, "table-plural").FixLabel);

        var renamed = Find(review, "column-style").Fix!(design);
        Assert.Equal("customer_id", renamed.Columns[1].Name);
        Assert.Equal("customer_id", renamed.ForeignKeys[0].Column);
        Assert.Equal(["customer_id"], renamed.Indexes[0].Columns);
    }

    [Fact]
    public void A_missing_audit_column_is_added_with_a_default_of_now()
    {
        var context = SnakeShop();
        var design = new TableDesign { Schema = "public", Name = "invoices", Columns = [Key("id") with { Type = "integer" }] };
        var added = Find(TableDesignAdvisor.Review(design, context), "audit:created_at").Fix!(design).Column("created_at")!;
        Assert.Equal(("timestamp with time zone", false, "now()"), (added.FullType, added.IsNullable, added.Default));
    }

    [Fact]
    public void Varchar_in_an_nvarchar_database_is_flagged()
    {
        var design = Invoices(Key("InvoiceId"), Col("Comment", "varchar", "500"));
        var fix = Find(TableDesignAdvisor.Review(design, Shop), "unicode").Fix!(design);
        Assert.Equal("nvarchar(500)", fix.Column("Comment")!.FullType);
    }

    [Fact]
    public void Reserved_words_are_pointed_out()
    {
        var review = TableDesignAdvisor.Review(Invoices(Key("InvoiceId"), Col("Order", "int")) with { Name = "User" }, Shop);
        Assert.Contains(review, s => s.Key == "reserved:User");
        Assert.Contains(review, s => s.Key == "reserved:Order");
    }

    [Theory]
    [InlineData("Customer", "Customers")]
    [InlineData("Category", "Categories")]
    [InlineData("Box", "Boxes")]
    [InlineData("order_line", "order_lines")]
    public void Plurals_round_trip(string singular, string plural)
    {
        Assert.Equal(plural, DesignContext.Pluralize(singular));
        Assert.Equal(singular, DesignContext.Singularize(plural));
    }

    [Theory]
    [InlineData("CustomerId", NamingStyle.Snake, "customer_id")]
    [InlineData("customer_id", NamingStyle.Pascal, "CustomerId")]
    [InlineData("HTTPStatus", NamingStyle.Snake, "http_status")]
    [InlineData("Order Notes", NamingStyle.Pascal, "OrderNotes")]
    public void Names_convert_between_styles(string name, NamingStyle style, string expected) =>
        Assert.Equal(expected, DesignContext.ToStyle(name, style));
}
